# Generated by Django 5.1.7 on 2025-10-04 07:39

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="StartupStory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "heading",
                    models.CharField(
                        help_text="Main title of the story", max_length=255
                    ),
                ),
                (
                    "subheading",
                    models.CharField(
                        blank=True, help_text="Optional subtitle", max_length=255
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        help_text="URL-friendly version of title",
                        max_length=255,
                        unique=True,
                    ),
                ),
                (
                    "summary",
                    models.TextField(help_text="Brief summary/excerpt (2-3 sentences)"),
                ),
                (
                    "content",
                    models.TextField(help_text="Main story content (supports HTML)"),
                ),
                (
                    "key_takeaways",
                    models.TextField(help_text="Key lessons learned (one per line)"),
                ),
                (
                    "challenges_faced",
                    models.TextField(
                        blank=True, help_text="Challenges the startup faced"
                    ),
                ),
                (
                    "solutions_implemented",
                    models.TextField(
                        blank=True, help_text="How they solved the challenges"
                    ),
                ),
                (
                    "featured_image",
                    models.URLField(blank=True, help_text="URL for main story image"),
                ),
                (
                    "video_url",
                    models.URLField(blank=True, help_text="YouTube or Vimeo URL"),
                ),
                (
                    "additional_images",
                    models.TextField(
                        blank=True, help_text="Additional image URLs (one per line)"
                    ),
                ),
                (
                    "industry",
                    models.CharField(
                        choices=[
                            ("technology", "Technology"),
                            ("healthcare", "Healthcare"),
                            ("finance", "Finance"),
                            ("education", "Education"),
                            ("ecommerce", "E-Commerce"),
                            ("ai_ml", "AI/ML"),
                            ("saas", "SaaS"),
                            ("other", "Other"),
                        ],
                        default="technology",
                        max_length=50,
                    ),
                ),
                (
                    "stage",
                    models.CharField(
                        choices=[
                            ("idea", "Idea"),
                            ("pre_seed", "Pre-Seed"),
                            ("seed", "Seed"),
                            ("series_a", "Series A"),
                            ("series_b", "Series B"),
                            ("growth", "Growth"),
                            ("exit", "Exit"),
                        ],
                        default="seed",
                        max_length=50,
                    ),
                ),
                (
                    "tags",
                    models.CharField(
                        blank=True, help_text="Comma-separated tags", max_length=255
                    ),
                ),
                (
                    "founder_name",
                    models.CharField(
                        blank=True, help_text="Name of the founder(s)", max_length=255
                    ),
                ),
                (
                    "company_name",
                    models.CharField(help_text="Name of the startup", max_length=255),
                ),
                ("founded_year", models.IntegerField(blank=True, null=True)),
                (
                    "is_featured",
                    models.BooleanField(
                        default=False, help_text="Show on homepage as featured"
                    ),
                ),
                (
                    "is_published",
                    models.BooleanField(
                        default=False, help_text="Make visible to public"
                    ),
                ),
                ("views_count", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("published_at", models.DateTimeField(blank=True, null=True)),
                (
                    "author",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Startup Story",
                "verbose_name_plural": "Startup Stories",
                "ordering": ["-created_at"],
            },
        ),
    ]
