# Generated by Django 5.1.7 on 2025-10-04 11:52

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0002_startupstory"),
    ]

    operations = [
        migrations.CreateModel(
            name="NeoStory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "header",
                    models.CharField(
                        help_text="Main title of the Neo story", max_length=255
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        help_text="URL-friendly version of title",
                        max_length=255,
                        unique=True,
                    ),
                ),
                ("main_image", models.URLField(help_text="URL for main story image")),
                (
                    "introduction",
                    models.TextField(
                        help_text="Brief introduction/excerpt (2-3 sentences)"
                    ),
                ),
                (
                    "sections",
                    models.JSONField(
                        default=list,
                        help_text='\n        JSON array of sections. Each section should have:\n        {\n            "subheading": "Section Title",\n            "paragraph": "Section content text",\n            "media_type": "image" or "video" or "none",\n            "media_url": "URL to image or video",\n            "media_caption": "Optional caption"\n        }\n        ',
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("technology", "Technology"),
                            ("innovation", "Innovation"),
                            ("entrepreneurship", "Entrepreneurship"),
                            ("leadership", "Leadership"),
                            ("culture", "Culture"),
                            ("social_impact", "Social Impact"),
                            ("design", "Design"),
                            ("other", "Other"),
                        ],
                        default="technology",
                        max_length=50,
                    ),
                ),
                (
                    "tags",
                    models.CharField(
                        blank=True, help_text="Comma-separated tags", max_length=255
                    ),
                ),
                (
                    "author_name",
                    models.CharField(
                        blank=True, help_text="Name of the author", max_length=255
                    ),
                ),
                (
                    "read_time",
                    models.IntegerField(
                        default=5, help_text="Estimated reading time in minutes"
                    ),
                ),
                (
                    "is_featured",
                    models.BooleanField(
                        default=False, help_text="Show on homepage as featured"
                    ),
                ),
                (
                    "is_published",
                    models.BooleanField(
                        default=False, help_text="Make visible to public"
                    ),
                ),
                ("views_count", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("published_at", models.DateTimeField(blank=True, null=True)),
                (
                    "author",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Neo Story",
                "verbose_name_plural": "Neo Stories",
                "ordering": ["-created_at"],
            },
        ),
    ]
