# Generated by Django 5.2.7 on 2025-10-05 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0004_sharxathon"),
    ]

    operations = [
        migrations.CreateModel(
            name="TechNews",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(help_text="Article headline", max_length=300),
                ),
                ("slug", models.SlugField(blank=True, max_length=350, unique=True)),
                (
                    "subtitle",
                    models.CharField(
                        blank=True,
                        help_text="Brief subtitle or tagline",
                        max_length=500,
                    ),
                ),
                (
                    "excerpt",
                    models.TextField(
                        help_text="Short summary/excerpt (max 500 chars)",
                        max_length=500,
                    ),
                ),
                (
                    "content",
                    models.TextField(help_text="Full article content (supports HTML)"),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("ai_ml", "AI & Machine Learning"),
                            ("blockchain", "Blockchain & Crypto"),
                            ("cloud", "Cloud Computing"),
                            ("cybersecurity", "Cybersecurity"),
                            ("mobile", "Mobile Development"),
                            ("web", "Web Development"),
                            ("iot", "Internet of Things"),
                            ("devops", "DevOps"),
                            ("data_science", "Data Science"),
                            ("quantum", "Quantum Computing"),
                            ("ar_vr", "AR/VR"),
                            ("5g", "5G & Networking"),
                            ("startup", "Startup News"),
                            ("product_launch", "Product Launch"),
                            ("funding", "Funding & Investment"),
                            ("tech_policy", "Tech Policy"),
                            ("other", "Other"),
                        ],
                        default="other",
                        help_text="Primary category",
                        max_length=50,
                    ),
                ),
                (
                    "tags",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text='Tags as JSON array: ["tag1", "tag2", "tag3"]',
                    ),
                ),
                (
                    "featured_image",
                    models.URLField(blank=True, help_text="Main article image URL"),
                ),
                (
                    "thumbnail_image",
                    models.URLField(
                        blank=True, help_text="Thumbnail image URL (for cards)"
                    ),
                ),
                (
                    "video_url",
                    models.URLField(
                        blank=True, help_text="Video URL (YouTube, Vimeo, etc.)"
                    ),
                ),
                (
                    "gallery_images",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text='Additional images as JSON array: ["url1", "url2"]',
                    ),
                ),
                (
                    "source_name",
                    models.CharField(
                        blank=True, help_text="Original source name", max_length=200
                    ),
                ),
                (
                    "source_url",
                    models.URLField(blank=True, help_text="Link to original article"),
                ),
                (
                    "author_name",
                    models.CharField(
                        blank=True, help_text="Article author", max_length=200
                    ),
                ),
                (
                    "author_bio",
                    models.TextField(blank=True, help_text="Author biography"),
                ),
                (
                    "author_avatar",
                    models.URLField(blank=True, help_text="Author avatar image URL"),
                ),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("low", "Low"),
                            ("medium", "Medium"),
                            ("high", "High"),
                            ("breaking", "Breaking News"),
                        ],
                        default="medium",
                        help_text="Article priority/importance",
                        max_length=20,
                    ),
                ),
                (
                    "read_time_minutes",
                    models.IntegerField(
                        default=5, help_text="Estimated reading time in minutes"
                    ),
                ),
                (
                    "views_count",
                    models.IntegerField(default=0, help_text="Number of views"),
                ),
                (
                    "likes_count",
                    models.IntegerField(default=0, help_text="Number of likes"),
                ),
                (
                    "shares_count",
                    models.IntegerField(default=0, help_text="Number of shares"),
                ),
                (
                    "related_links",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text='Related links: [{"title": "Link", "url": "https://..."}]',
                    ),
                ),
                (
                    "key_points",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text='Key takeaways: ["Point 1", "Point 2", "Point 3"]',
                    ),
                ),
                (
                    "is_published",
                    models.BooleanField(
                        default=False, help_text="Publish this article?"
                    ),
                ),
                (
                    "is_featured",
                    models.BooleanField(
                        default=False, help_text="Feature on homepage?"
                    ),
                ),
                (
                    "is_breaking",
                    models.BooleanField(
                        default=False, help_text="Mark as breaking news?"
                    ),
                ),
                (
                    "is_trending",
                    models.BooleanField(default=False, help_text="Mark as trending?"),
                ),
                (
                    "published_at",
                    models.DateTimeField(
                        blank=True, help_text="Publication date", null=True
                    ),
                ),
                (
                    "meta_description",
                    models.CharField(
                        blank=True, help_text="SEO meta description", max_length=160
                    ),
                ),
                (
                    "meta_keywords",
                    models.CharField(
                        blank=True,
                        help_text="SEO keywords (comma-separated)",
                        max_length=255,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Tech News Article",
                "verbose_name_plural": "Tech News Articles",
                "ordering": ["-published_at", "-created_at"],
                "indexes": [
                    models.Index(fields=["slug"], name="authenticat_slug_481160_idx"),
                    models.Index(
                        fields=["category"], name="authenticat_categor_aeb1d7_idx"
                    ),
                    models.Index(
                        fields=["is_published", "-published_at"],
                        name="authenticat_is_publ_454946_idx",
                    ),
                    models.Index(
                        fields=["is_featured"], name="authenticat_is_feat_0f1462_idx"
                    ),
                    models.Index(
                        fields=["is_breaking"], name="authenticat_is_brea_47a66e_idx"
                    ),
                ],
            },
        ),
    ]
