# Generated by Django 5.1.7 on 2025-10-05 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0005_technews"),
    ]

    operations = [
        migrations.CreateModel(
            name="TalkEpisode",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "episode_number",
                    models.IntegerField(
                        help_text="Episode number (e.g., 1, 2, 3)", unique=True
                    ),
                ),
                ("title", models.CharField(help_text="Episode title", max_length=300)),
                ("slug", models.SlugField(blank=True, max_length=300, unique=True)),
                (
                    "header",
                    models.CharField(
                        help_text="Episode header/tagline", max_length=500
                    ),
                ),
                (
                    "youtube_url",
                    models.URLField(help_text="YouTube video URL or embed URL"),
                ),
                (
                    "thumbnail_url",
                    models.URLField(
                        blank=True, help_text="Custom thumbnail URL", null=True
                    ),
                ),
                ("description", models.TextField(help_text="Full episode description")),
                (
                    "key_takeaways",
                    models.JSONField(
                        default=list,
                        help_text="List of key takeaways (e.g., ['Point 1', 'Point 2', 'Point 3'])",
                    ),
                ),
                (
                    "speaker_panels",
                    models.JSONField(
                        default=list,
                        help_text="List of speaker objects with name, title, bio, avatar_url, social_links",
                    ),
                ),
                (
                    "duration_minutes",
                    models.IntegerField(
                        default=60, help_text="Episode duration in minutes"
                    ),
                ),
                (
                    "published_at",
                    models.DateTimeField(help_text="When the episode was published"),
                ),
                (
                    "is_published",
                    models.BooleanField(
                        default=True, help_text="Is this episode published?"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Talk Episode",
                "verbose_name_plural": "Talk Episodes",
                "ordering": ["-episode_number"],
            },
        ),
    ]
