# Generated by Django 5.2.7 on 2025-10-06 15:42

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0006_talkepisode'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoboticsNews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Main headline', max_length=255)),
                ('subtitle', models.CharField(blank=True, help_text='Optional subtitle', max_length=255)),
                ('slug', models.SlugField(help_text='URL-friendly version', max_length=255, unique=True)),
                ('summary', models.TextField(help_text='Brief article summary (2-3 sentences)')),
                ('content', models.TextField(help_text='Full article content (supports HTML)')),
                ('excerpt', models.TextField(blank=True, help_text='Short excerpt for previews')),
                ('featured_image', models.URLField(help_text='Main article image URL')),
                ('additional_images', models.TextField(blank=True, help_text='Additional image URLs (one per line)')),
                ('video_url', models.URLField(blank=True, help_text='YouTube/Vimeo video URL')),
                ('category', models.CharField(choices=[('ai_robotics', 'AI & Robotics'), ('industrial', 'Industrial Robotics'), ('medical', 'Medical Robotics'), ('autonomous', 'Autonomous Vehicles'), ('space', 'Space Robotics'), ('consumer', 'Consumer Robotics'), ('research', 'Research & Development'), ('entertainment', 'Entertainment Robotics'), ('military', 'Military & Defense'), ('agriculture', 'Agricultural Robotics'), ('manufacturing', 'Manufacturing'), ('other', 'Other')], default='ai_robotics', max_length=50)),
                ('tags', models.CharField(blank=True, help_text='Comma-separated tags', max_length=255)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='medium', max_length=20)),
                ('source_name', models.CharField(blank=True, help_text='Original source', max_length=255)),
                ('source_url', models.URLField(blank=True, help_text='Link to original article')),
                ('author_name', models.CharField(blank=True, help_text='Article author', max_length=255)),
                ('robot_type', models.CharField(blank=True, help_text='Type of robot discussed', max_length=255)),
                ('company_mentioned', models.CharField(blank=True, help_text='Companies mentioned', max_length=255)),
                ('technology_focus', models.CharField(blank=True, help_text='Key technologies', max_length=255)),
                ('is_featured', models.BooleanField(default=False, help_text='Feature on homepage')),
                ('is_published', models.BooleanField(default=True, help_text='Visible to public')),
                ('is_breaking', models.BooleanField(default=False, help_text='Breaking news priority')),
                ('views_count', models.IntegerField(default=0)),
                ('likes_count', models.IntegerField(default=0)),
                ('shares_count', models.IntegerField(default=0)),
                ('comments_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('reading_time', models.IntegerField(default=5, help_text='Estimated reading time in minutes')),
                ('difficulty_level', models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced'), ('expert', 'Expert')], default='intermediate', max_length=20)),
            ],
            options={
                'verbose_name': 'Robotics News Article',
                'verbose_name_plural': 'Robotics News Articles',
                'ordering': ['-created_at'],
            },
        ),
    ]
