# Generated by Django 5.1.7 on 2025-10-10 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0009_alter_comment_content_type_neoproject"),
    ]

    operations = [
        migrations.AddField(
            model_name="talkepisode",
            name="featured_screens",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="List of featured screen URLs (e.g., ['https://...', 'https://...'])",
            ),
        ),
    ]
