# Generated by Django 5.1.7 on 2025-10-10 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0010_talkepisode_featured_screens"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="talkepisode",
            name="featured_screens",
        ),
        migrations.AddField(
            model_name="talkepisode",
            name="featured_screen",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text='Featured screen object: {"url": "https://...", "type": "image" or "video", "is_featured": true/false}',
                null=True,
            ),
        ),
    ]
