# Generated by Django 5.1.7 on 2025-10-10 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0012_neostory_featured_screen"),
    ]

    operations = [
        migrations.AddField(
            model_name="roboticsnews",
            name="featured_screen",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text='\n        Featured screen object with format:\n        {\n            "url": "https://example.com/image.jpg or youtube.com/watch?v=...",\n            "type": "image" or "video",\n            "is_featured": true or false\n        }\n        ',
                null=True,
            ),
        ),
    ]
