# Generated by Django 5.1.7 on 2025-10-10 20:33

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0016_startupstory_sharxathon_featured_screen"),
    ]

    operations = [
        migrations.CreateModel(
            name="Event",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(help_text="Event name/title", max_length=255),
                ),
                ("slug", models.SlugField(blank=True, max_length=300, unique=True)),
                (
                    "description",
                    models.TextField(help_text="Brief description of the event"),
                ),
                (
                    "details",
                    models.TextField(help_text="Detailed information about the event"),
                ),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("past", "Past Event"),
                            ("recent", "Recent Event"),
                            ("upcoming", "Upcoming Event"),
                        ],
                        default="upcoming",
                        max_length=20,
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("conference", "Conference"),
                            ("workshop", "Workshop"),
                            ("seminar", "Seminar"),
                            ("hackathon", "Hackathon"),
                            ("meetup", "Meetup"),
                            ("webinar", "Webinar"),
                            ("networking", "Networking"),
                            ("summit", "Summit"),
                            ("expo", "Expo"),
                            ("other", "Other"),
                        ],
                        default="conference",
                        max_length=50,
                    ),
                ),
                (
                    "location",
                    models.CharField(
                        help_text="Event location or 'Virtual'", max_length=255
                    ),
                ),
                ("is_virtual", models.BooleanField(default=False)),
                (
                    "venue_details",
                    models.TextField(
                        blank=True, help_text="Detailed venue information"
                    ),
                ),
                ("event_date", models.DateField(help_text="Event date")),
                ("start_time", models.TimeField(help_text="Event start time")),
                ("end_time", models.TimeField(help_text="Event end time")),
                (
                    "event_timezone",
                    models.CharField(
                        default="UTC",
                        help_text="Timezone (e.g., 'America/New_York', 'Asia/Kolkata')",
                        max_length=50,
                    ),
                ),
                ("featured_image", models.URLField(help_text="Main event image URL")),
                (
                    "thumbnail_image",
                    models.URLField(
                        blank=True, help_text="Thumbnail for cards/sliders"
                    ),
                ),
                (
                    "gallery_images",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="JSON array of image URLs for event gallery",
                    ),
                ),
                (
                    "benefits",
                    models.JSONField(
                        default=list,
                        help_text='JSON array of event benefits:\n        [\n            "Networking opportunities",\n            "Free meals and refreshments",\n            "Certificate of attendance",\n            "Workshop materials included"\n        ]\n        ',
                    ),
                ),
                (
                    "key_highlights",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text='JSON array of key highlights:\n        [\n            "Keynote by industry leaders",\n            "Panel discussions",\n            "Interactive workshops",\n            "Product demos"\n        ]\n        ',
                    ),
                ),
                (
                    "speakers",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text='JSON array of speakers:\n        [\n            {\n                "name": "John Doe",\n                "title": "CEO, TechCorp",\n                "bio": "Expert in AI and ML",\n                "photo": "https://example.com/photo.jpg"\n            }\n        ]\n        ',
                    ),
                ),
                (
                    "registration_url",
                    models.URLField(blank=True, help_text="External registration link"),
                ),
                ("registration_deadline", models.DateTimeField(blank=True, null=True)),
                ("is_registration_open", models.BooleanField(default=True)),
                (
                    "max_participants",
                    models.IntegerField(default=0, help_text="0 means unlimited"),
                ),
                ("current_participants", models.IntegerField(default=0)),
                ("is_free", models.BooleanField(default=True)),
                (
                    "ticket_price",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        help_text="Ticket price in USD",
                        max_digits=10,
                    ),
                ),
                (
                    "early_bird_price",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        default=0.0,
                        max_digits=10,
                        null=True,
                    ),
                ),
                ("early_bird_deadline", models.DateTimeField(blank=True, null=True)),
                (
                    "organizer_name",
                    models.CharField(default="NeoSharX Team", max_length=255),
                ),
                ("organizer_email", models.EmailField(blank=True, max_length=254)),
                ("organizer_phone", models.CharField(blank=True, max_length=20)),
                ("organizer_website", models.URLField(blank=True)),
                (
                    "event_website",
                    models.URLField(blank=True, help_text="Official event website"),
                ),
                (
                    "social_links",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text='JSON object of social links:\n        {\n            "twitter": "https://twitter.com/event",\n            "linkedin": "https://linkedin.com/event",\n            "facebook": "https://facebook.com/event",\n            "instagram": "https://instagram.com/event"\n        }\n        ',
                    ),
                ),
                (
                    "sponsors",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text='JSON array of sponsors:\n        [\n            {\n                "name": "TechCorp",\n                "logo": "https://example.com/logo.png",\n                "tier": "Gold",\n                "website": "https://techcorp.com"\n            }\n        ]\n        ',
                    ),
                ),
                (
                    "agenda",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text='JSON array of agenda items:\n        [\n            {\n                "time": "09:00 AM",\n                "title": "Registration & Breakfast",\n                "description": "Check-in and networking",\n                "speaker": ""\n            }\n        ]\n        ',
                    ),
                ),
                (
                    "is_featured",
                    models.BooleanField(
                        default=False, help_text="Show as featured event"
                    ),
                ),
                (
                    "is_published",
                    models.BooleanField(
                        default=False, help_text="Make visible to public"
                    ),
                ),
                (
                    "display_order",
                    models.IntegerField(
                        default=0, help_text="Order in slider (lower number = first)"
                    ),
                ),
                ("views_count", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("published_at", models.DateTimeField(blank=True, null=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Event",
                "verbose_name_plural": "Events",
                "ordering": ["display_order", "-event_date"],
                "indexes": [
                    models.Index(
                        fields=["event_type", "is_published"],
                        name="authenticat_event_t_2cdf12_idx",
                    ),
                    models.Index(
                        fields=["event_date", "is_featured"],
                        name="authenticat_event_d_e9e332_idx",
                    ),
                    models.Index(
                        fields=["display_order"], name="authenticat_display_535e4c_idx"
                    ),
                ],
            },
        ),
    ]
