# Generated by Django 5.1.7 on 2025-10-12 07:45

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0017_event"),
    ]

    operations = [
        migrations.CreateModel(
            name="YouTubeVideo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(help_text="Video title", max_length=255)),
                (
                    "description",
                    models.TextField(blank=True, help_text="Video description"),
                ),
                ("slug", models.SlugField(blank=True, max_length=300, unique=True)),
                (
                    "youtube_url",
                    models.URLField(
                        help_text="Full YouTube URL (e.g., https://www.youtube.com/watch?v=VIDEO_ID or https://youtube.com/shorts/SHORT_ID)"
                    ),
                ),
                (
                    "video_id",
                    models.CharField(
                        help_text="YouTube video ID (extracted from URL)", max_length=50
                    ),
                ),
                (
                    "embed_url",
                    models.URLField(blank=True, help_text="Auto-generated embed URL"),
                ),
                (
                    "video_type",
                    models.CharField(
                        choices=[
                            ("video", "YouTube Video"),
                            ("short", "YouTube Short"),
                        ],
                        default="video",
                        max_length=20,
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("tech_talks", "Tech Talks"),
                            ("tutorials", "Tutorials"),
                            ("startup_stories", "Startup Stories"),
                            ("hackathons", "Hackathons"),
                            ("events", "Events"),
                            ("interviews", "Interviews"),
                            ("demos", "Product Demos"),
                            ("other", "Other"),
                        ],
                        default="tech_talks",
                        max_length=50,
                    ),
                ),
                (
                    "tags",
                    models.CharField(
                        blank=True, help_text="Comma-separated tags", max_length=255
                    ),
                ),
                (
                    "thumbnail_url",
                    models.URLField(
                        blank=True,
                        help_text="Custom thumbnail URL (if not using YouTube default)",
                    ),
                ),
                (
                    "auto_thumbnail",
                    models.URLField(
                        blank=True, help_text="Auto-fetched YouTube thumbnail"
                    ),
                ),
                (
                    "is_featured",
                    models.BooleanField(
                        default=False, help_text="Show prominently on homepage"
                    ),
                ),
                (
                    "is_published",
                    models.BooleanField(
                        default=False, help_text="Make visible to public"
                    ),
                ),
                (
                    "display_order",
                    models.IntegerField(
                        default=0, help_text="Display order (lower = first)"
                    ),
                ),
                (
                    "autoplay",
                    models.BooleanField(
                        default=True, help_text="Enable autoplay on homepage"
                    ),
                ),
                (
                    "duration",
                    models.CharField(
                        blank=True,
                        help_text="Video duration (e.g., '5:30')",
                        max_length=20,
                    ),
                ),
                (
                    "view_count",
                    models.IntegerField(default=0, help_text="YouTube view count"),
                ),
                (
                    "like_count",
                    models.IntegerField(default=0, help_text="YouTube like count"),
                ),
                (
                    "published_date",
                    models.DateField(
                        blank=True, help_text="Original YouTube publish date", null=True
                    ),
                ),
                (
                    "internal_views",
                    models.IntegerField(default=0, help_text="Views on our platform"),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "YouTube Video",
                "verbose_name_plural": "YouTube Videos",
                "ordering": ["display_order", "-created_at"],
                "indexes": [
                    models.Index(
                        fields=["video_type", "is_published"],
                        name="authenticat_video_t_fb669f_idx",
                    ),
                    models.Index(
                        fields=["category", "is_featured"],
                        name="authenticat_categor_b24a7e_idx",
                    ),
                    models.Index(
                        fields=["display_order"], name="authenticat_display_73cef2_idx"
                    ),
                ],
            },
        ),
    ]
