# Generated by Django 5.1.7 on 2025-10-12 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0018_youtubevideo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="end_time",
            field=models.TimeField(blank=True, help_text="Event end time", null=True),
        ),
        migrations.AlterField(
            model_name="event",
            name="event_timezone",
            field=models.CharField(
                blank=True,
                default="UTC",
                help_text="Timezone (e.g., 'America/New_York', 'Asia/Kolkata')",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="event",
            name="start_time",
            field=models.TimeField(blank=True, help_text="Event start time", null=True),
        ),
    ]
