# Generated by Django 5.1.7 on 2025-10-12 15:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "authentication",
            "0019_alter_event_end_time_alter_event_event_timezone_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="UserPreference",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "user_type",
                    models.CharField(
                        choices=[
                            ("student", "Student"),
                            ("working_professional", "Working Professional"),
                            ("tech_enthusiast", "Tech Enthusiast"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "interest",
                    models.CharField(
                        choices=[
                            ("talks", "Talks"),
                            ("startups", "Startups"),
                            ("neo_stories", "Neo Stories"),
                            ("projects", "Projects"),
                            ("sharxathons", "SharXathons"),
                            ("robosharx", "RoboSharX"),
                            ("tech_news", "Tech News"),
                        ],
                        max_length=50,
                    ),
                ),
                ("email", models.EmailField(blank=True, max_length=254, null=True)),
                (
                    "provider",
                    models.CharField(
                        blank=True,
                        help_text="google or linkedin",
                        max_length=20,
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="preferences",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "User Preference",
                "verbose_name_plural": "User Preferences",
                "ordering": ["-created_at"],
            },
        ),
    ]
