# Generated by Django 5.1.7 on 2025-10-18 05:36

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0021_alter_customuser_phone_number"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProjectOwner",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Full name of the project owner", max_length=255
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        help_text="URL-friendly version of name",
                        max_length=255,
                        unique=True,
                    ),
                ),
                (
                    "bio",
                    models.TextField(
                        blank=True, help_text="Short biography of the project owner"
                    ),
                ),
                (
                    "avatar",
                    models.URLField(blank=True, help_text="Profile picture URL"),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, help_text="Contact email", max_length=254
                    ),
                ),
                (
                    "phone",
                    models.CharField(
                        blank=True, help_text="Contact phone number", max_length=20
                    ),
                ),
                (
                    "location",
                    models.CharField(
                        blank=True, help_text="Location/City, Country", max_length=255
                    ),
                ),
                (
                    "linkedin_url",
                    models.URLField(blank=True, help_text="LinkedIn profile URL"),
                ),
                (
                    "github_url",
                    models.URLField(blank=True, help_text="GitHub profile URL"),
                ),
                (
                    "twitter_url",
                    models.URLField(blank=True, help_text="Twitter/X profile URL"),
                ),
                (
                    "website_url",
                    models.URLField(blank=True, help_text="Personal website URL"),
                ),
                (
                    "title",
                    models.CharField(
                        blank=True,
                        help_text="Professional title (e.g., Software Engineer, Student)",
                        max_length=255,
                    ),
                ),
                (
                    "company",
                    models.CharField(
                        blank=True,
                        help_text="Current company/organization",
                        max_length=255,
                    ),
                ),
                (
                    "experience_years",
                    models.IntegerField(
                        blank=True, help_text="Years of experience", null=True
                    ),
                ),
                (
                    "skills",
                    models.JSONField(
                        default=list, help_text="Array of skills/technologies"
                    ),
                ),
                (
                    "interests",
                    models.JSONField(default=list, help_text="Array of interests"),
                ),
                (
                    "is_featured",
                    models.BooleanField(
                        default=False, help_text="Feature this profile"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, help_text="Is this profile active"
                    ),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Project Owner",
                "verbose_name_plural": "Project Owners",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddField(
            model_name="neoproject",
            name="owner",
            field=models.ForeignKey(
                blank=True,
                help_text="Project owner profile",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="projects",
                to="authentication.projectowner",
            ),
        ),
        migrations.CreateModel(
            name="ProjectLink",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="Display name for the link", max_length=255
                    ),
                ),
                ("url", models.URLField(help_text="URL of the link")),
                (
                    "link_type",
                    models.CharField(
                        choices=[
                            ("website", "Website"),
                            ("demo", "Live Demo"),
                            ("documentation", "Documentation"),
                            ("api", "API"),
                            ("blog", "Blog"),
                            ("portfolio", "Portfolio"),
                            ("social", "Social Media"),
                            ("other", "Other"),
                        ],
                        default="other",
                        help_text="Type/category of the link",
                        max_length=20,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Optional description of what this link contains",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, help_text="Is this link active/visible"
                    ),
                ),
                (
                    "order",
                    models.IntegerField(
                        default=0,
                        help_text="Display order (lower numbers appear first)",
                    ),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "project",
                    models.ForeignKey(
                        help_text="Project this link belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="additional_links",
                        to="authentication.neoproject",
                    ),
                ),
            ],
            options={
                "verbose_name": "Project Link",
                "verbose_name_plural": "Project Links",
                "ordering": ["order", "created_at"],
                "unique_together": {("project", "title")},
            },
        ),
    ]
