# Generated by Django 5.1.7 on 2025-10-18 09:20

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0022_projectowner_neoproject_owner_projectlink"),
    ]

    operations = [
        migrations.CreateModel(
            name="HackathonMentor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Full name of the mentor", max_length=255
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        help_text="URL-friendly version of name",
                        max_length=255,
                        unique=True,
                    ),
                ),
                (
                    "bio",
                    models.TextField(
                        blank=True, help_text="Short biography of the mentor"
                    ),
                ),
                (
                    "avatar",
                    models.URLField(blank=True, help_text="Profile picture URL"),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, help_text="Contact email", max_length=254
                    ),
                ),
                (
                    "phone",
                    models.CharField(
                        blank=True, help_text="Contact phone number", max_length=20
                    ),
                ),
                (
                    "location",
                    models.CharField(
                        blank=True, help_text="Location/City, Country", max_length=255
                    ),
                ),
                (
                    "linkedin_url",
                    models.URLField(blank=True, help_text="LinkedIn profile URL"),
                ),
                (
                    "github_url",
                    models.URLField(blank=True, help_text="GitHub profile URL"),
                ),
                (
                    "twitter_url",
                    models.URLField(blank=True, help_text="Twitter/X profile URL"),
                ),
                (
                    "website_url",
                    models.URLField(blank=True, help_text="Personal website URL"),
                ),
                (
                    "title",
                    models.CharField(
                        blank=True,
                        help_text="Professional title (e.g., Senior Engineer, Tech Lead)",
                        max_length=255,
                    ),
                ),
                (
                    "company",
                    models.CharField(
                        blank=True,
                        help_text="Current company/organization",
                        max_length=255,
                    ),
                ),
                (
                    "experience_years",
                    models.IntegerField(
                        blank=True, help_text="Years of experience", null=True
                    ),
                ),
                (
                    "skills",
                    models.JSONField(
                        default=list, help_text="Array of skills/technologies"
                    ),
                ),
                (
                    "expertise_areas",
                    models.JSONField(
                        default=list,
                        help_text="Areas of expertise (e.g., AI, Web Dev, Mobile)",
                    ),
                ),
                (
                    "is_featured",
                    models.BooleanField(default=False, help_text="Feature this mentor"),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, help_text="Is this mentor profile active"
                    ),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Hackathon Mentor",
                "verbose_name_plural": "Hackathon Mentors",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddField(
            model_name="sharxathon",
            name="mentors",
            field=models.ManyToManyField(
                blank=True,
                help_text="Mentors assigned to this hackathon",
                related_name="hackathons",
                to="authentication.hackathonmentor",
            ),
        ),
        migrations.CreateModel(
            name="HackathonMentorLink",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="Link title (e.g., 'My Portfolio', 'Resume')",
                        max_length=255,
                    ),
                ),
                ("url", models.URLField(help_text="Link URL")),
                (
                    "link_type",
                    models.CharField(
                        choices=[
                            ("website", "Website"),
                            ("portfolio", "Portfolio"),
                            ("resume", "Resume/CV"),
                            ("linkedin", "LinkedIn"),
                            ("github", "GitHub"),
                            ("twitter", "Twitter"),
                            ("blog", "Blog"),
                            ("youtube", "YouTube"),
                            ("other", "Other"),
                        ],
                        default="other",
                        help_text="Type of link",
                        max_length=20,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, help_text="Optional description of the link"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, help_text="Is this link active"),
                ),
                ("order", models.IntegerField(default=0, help_text="Display order")),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "mentor",
                    models.ForeignKey(
                        help_text="Mentor this link belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="additional_links",
                        to="authentication.hackathonmentor",
                    ),
                ),
            ],
            options={
                "verbose_name": "Mentor Link",
                "verbose_name_plural": "Mentor Links",
                "ordering": ["order", "created_at"],
                "unique_together": {("mentor", "title")},
            },
        ),
    ]
