# Generated by Django 5.1.7 on 2025-10-18 12:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0023_hackathonmentor_sharxathon_mentors_and_more"),
    ]

    operations = []
